/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#1a1e00',
        'surface-container': '#edeeed',
        'tertiary-container': '#4c5500',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#bed100',
        'on-secondary-fixed-variant': '#474746',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#636262',
        'surface-container-highest': '#e1e3e2',
        'on-primary-fixed-variant': '#23501e',
        'on-tertiary': '#ffffff',
        'secondary-container': '#e2dfde',
        'tertiary-fixed': '#d9ef00',
        'on-background': '#191c1c',
        'on-primary-container': '#9dd090',
        'on-primary': '#ffffff',
        'primary-fixed': '#bcf0ae',
        'on-primary-fixed': '#002201',
        'surface-container-high': '#e7e8e7',
        'inverse-surface': '#2e3131',
        outline: '#72796e',
        'surface-container-low': '#f3f4f3',
        'inverse-on-surface': '#f0f1f0',
        primary: '#154212',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#c8c6c5',
        tertiary: '#363d00',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#a1d494',
        background: '#f9f9f8',
        'secondary-fixed': '#e5e2e1',
        'on-tertiary-container': '#bacd00',
        'surface-bright': '#f9f9f8',
        secondary: '#5f5e5e',
        'primary-container': '#2d5a27',
        'surface-dim': '#d9dad9',
        'surface-variant': '#e1e3e2',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#434b00',
        'on-secondary-fixed': '#1c1b1b',
        'primary-fixed-dim': '#a1d494',
        surface: '#f9f9f8',
        'on-surface': '#191c1c',
        error: '#ba1a1a',
        'outline-variant': '#c2c9bb',
        'on-surface-variant': '#42493e',
        'surface-tint': '#3b6934',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        '2xl': '48px',
        xl: '32px',
        unit: '4px',
        'container-padding': '20px',
        'touch-target-min': '48px',
        md: '16px',
        xs: '4px',
        sm: '8px',
        lg: '24px',
      },
      fontFamily: {
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
